
export const texts = {
    en: {
        professionalProfile: "Professional Profile",
        projects: "Projects",
        skills: "Skills",
        experience: "Experience",
        contact: "Contact",
        title: "Full Stack Developer",
        titleDesc: "Building Software Since 2022",
        professionalText: "I'm a Full Stack Developer passionate about building solid, user-centered interfaces backed by robust engineering. With 2 years of experience collaborating with creative agencies, I bring a blend of technical precision and strong problem-solving. I’ve worked remotely with diverse teams to deliver reliable digital solutions and I've been recognized as a practical, efficient, and adaptable developer.",
        myWork: "My Work",
        myWorkDesc: "Some projects I've worked on.",
        myWorkEtb1: "ETB Server Inventory",
        myWorkEtb2: "A very intuitive project built with the purpose of helping the data base area in the management of the servers inventory.",
        myWorkSena1: "Automatic Payroll System",
        myWorkSena2: "Built with the purpose of helping companies generating automatic-generated payrolls for the employees.",
        skillsDesc: "My Coding Skills",
        skillsDesc2: "Click for more info",
        htmlDesc: "I've worked with HTML in three projects, including two personal projects and this portfolio. Most of my websites achieve great UI quickly thanks to the use of the Bootstrap library.",
        jsDesc: "Proficient in building both front-end and back-end features with JavaScript. I've developed all my projects using this language, creating intuitive interfaces and solid application logic.",
        cssDesc: "A core front-end technology I use in all my projects. I've worked with animations using keyframes and have used CSS since the beginning of my development career.",
        reactDesc: "Fast, modern, and visually appealing. I used React to build this portfolio, achieving excellent interactivity and UI design efficiently.",
        gitDesc: "Proficient in using Git for version control. It's my preferred tool to keep code safe, organized, and maintainable. I've used it in all my projects.",
        pythonDesc: "Experience with the Django framework and Scikit-learn across different projects. During my time at SENA, I was part of a team project built with Python and Django. I worked with OOP concepts and integrated databases using Django.",
        javaDesc: "Experience with Spring Boot. During my time at ETB, I helped lead the development of a company project using Java and Spring Boot. I worked with OOP principles and integrated MySQL databases using Spring Boot and JDBC.",
        mySqlDesc: "I've used MySQL as the database management system in all my projects. I continue learning new features, and in the future, I plan to explore additional DBMS options, including non-relational databases.",
        experienceDesc: "click/hover for more info",
        experienceEtb: "During a 6-month contract, I led a development team in building a project using new technologies such as Java Spring Boot. I was recognized for being an efficient, responsible, and fast-learning developer.",
        experienceSena: "Certified as a Technologist in Software Analysis and Development, I have collaborated with teams to solve real-world problems and built projects using industry-standard tools.",
        contactDesc: "Click for more info",
        contactName: "Name",
        contactMessage: "Message",
        contactButton: "Send",
        messageSent: "Message Sent"
    },
    es: {
        professionalProfile: "Perfil Profesional",
        projects: "Proyectos",
        skills: "Habilidades",
        experience: "Experiencia",
        contact: "Contacto",
        title: "Desarrollador Full Stack",
        titleDesc: "Construyendo software desde 2022",
        professionalText: "Soy un Desarrollador Full Stack apasionado por crear interfaces sólidas y centradas en el usuario, respaldadas por ingeniería robusta. Con 2 años de experiencia colaborando con agencias creativas, aporto una mezcla de precisión técnica y fuerte capacidad para resolver problemas. He trabajado de forma remota con equipos diversos para entregar soluciones digitales confiables y he sido reconocido como un desarrollador práctico, eficiente y adaptable.",
        myWork: "Mi Trabajo",
        myWorkDesc: "Algunos proyectos en los que trabaje.",
        myWorkEtb1: "Inventario de Servidores ETB",
        myWorkEtb2: "Un proyecto creado con el propósito de apoyar al área de bases de datos en la gestión del inventario de servidores.",
        myWorkSena1: "Sistema automatico de Nomina",
        myWorkSena2: "Creado con el propósito de ayudar a las empresas generando nóminas automáticas para sus empleados.",
        skillsDesc: "Mi Habilidad Programando",
        skillsDesc2: "Click para mas información",
        htmlDesc: "He trabajado con HTML en tres proyectos, incluyendo dos proyectos personales y este portafolio. La mayoría de mis sitios web logran una gran interfaz rápidamente gracias al uso de la librería Bootstrap.",
        jsDesc: "Competente en construir funcionalidades tanto de front-end como de back-end con JavaScript. He desarrollado todos mis proyectos usando este lenguaje, creando interfaces intuitivas y una lógica de aplicación sólida. ",
        cssDesc: "Una tecnología esencial de front-end que uso en todos mis proyectos. He trabajado con animaciones usando keyframes y he utilizado CSS desde el inicio de mi carrera en desarrollo.",
        reactDesc: "Rápido, moderno y visualmente atractivo. Usé React para construir este portafolio, logrando una excelente interactividad y diseño de interfaz de manera eficiente.",
        gitDesc: "Competente en el uso de Git para control de versiones. Es mi herramienta preferida para mantener el código seguro, organizado y mantenible. La he usado en todos mis proyectos.",
        pythonDesc: "Experiencia con el framework Django y Scikit-learn en diferentes proyectos. Durante mi tiempo en el SENA, fui parte de un proyecto en equipo construido con Python y Django. Trabajé con conceptos de POO e integré bases de datos usando Django.",
        javaDesc: "Experiencia con Spring Boot. Durante mi tiempo en ETB, ayudé a liderar el desarrollo de un proyecto empresarial usando Java y Spring Boot. Trabajé con principios de POO e integré bases de datos MySQL usando Spring Boot y JDBC.",
        mySqlDesc: "He usado MySQL como sistema de gestión de bases de datos en todos mis proyectos. Sigo aprendiendo nuevas funciones y, en el futuro, planeo explorar otras opciones de SGBD, incluyendo bases de datos no relacionales.",
        experienceDesc: "click/hover para mas información",
        experienceEtb: "Durante un contrato de 6 meses, lideré un equipo de desarrollo en la construcción de un proyecto usando nuevas tecnologías como Java Spring Boot. Fui reconocido por ser un desarrollador eficiente, responsable y de rápido aprendizaje.",
        experienceSena: "Certificado como Tecnólogo en Análisis y Desarrollo de Software, he colaborado con equipos para resolver problemas del mundo real y he construido proyectos usando herramientas estándar de la industria.",
        contactDesc: "Click para mas información",
        contactName: "Nombre",
        contactMessage: "Mensaje",
        contactButton: "Enviar",
        messageSent: "Mensaje Enviado"
    }
};